project:
  type: website

website:
  title: "Research Guide"
  navbar:
    logo: images/RDA_Logotype_CMYK.png
    logo-href: https://www.rd-alliance.org/groups/optical-radiation-exposure-and-visual-experience-data-wg/activity/
    left:
      - href: index.qmd
        text: Home
      - contributing.qmd
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Repository
            href: https://github.com/RDA-WG-VisualExperienceData/ResearcherGuide
            target: _blank
          - text: Report an Error
            href: https://github.com/RDA-WG-VisualExperienceData/ResearcherGuide/issues
            target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

