project:
  type: manuscript

website:
  title: "Researcher Guide"
  site-url: https://rda-wg-visualexperiencedata.github.io/ResearcherGuide/
  repo-url: https://github.com/RDA-WG-VisualExperienceData/ResearcherGuide
  issue-url: https://github.com/RDA-WG-VisualExperienceData/ResearcherGuide/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: images/RDA_Logotype_CMYK.png
    logo-href: https://www.rd-alliance.org/groups/optical-radiation-exposure-and-visual-experience-data-wg/activity/
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Contributing"
        href: contributing.qmd
    right:
      - icon: github
        href: https://github.com/RDA-WG-VisualExperienceData/ResearcherGuide
        aria-label: Quarto GitHub
  page-footer:
    center: |
      [![](assets/logo-mpi.png){width=180pt}](https://www.kyb.tuebingen.mpg.de/en)
    right: "[Imprint](imprint.qmd)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    comments:
      hypothesis: true
    format:
    toc-location: left
    toc-depth: 3
    toc-expand: 2
  # typst:
  #   toc: true
  #   toc-depth: 3
  #   number-sections: true
  #   papersize: a4
  #   fig-format: png
  #   fig-dpi: 600
  #   fig-height: 3.45
format-links:
  - html
  # - format: typst
  #   text: PDF
  #   icon: file-pdf


date: last-modified

language:
  title-block-published: "Last modified:"

execute:
  echo: false
  warning: false
  message: false
  error: false
  freeze: auto
